"""Add analytics and monitoring tables

Revision ID: 0d6804a69007
Revises: 002_add_image_support
Create Date: 2025-08-21 10:56:20.892214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d6804a69007'
down_revision: Union[str, None] = '002_add_image_support'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('flagged_count', sa.Integer(), nullable=False),
    sa.Column('clean_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('avg_processing_time', sa.Float(), nullable=True),
    sa.Column('total_file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_analytics_date'), 'daily_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_analytics_id'), 'daily_analytics', ['id'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(), nullable=True),
    sa.Column('metric_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_system_metrics_metric_name'), 'system_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.alter_column('image_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_image_analysis_moderation_event_id', table_name='image_analysis')
    op.create_index(op.f('ix_image_analysis_id'), 'image_analysis', ['id'], unique=False)
    op.alter_column('moderation_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderation_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_image_analysis_id'), table_name='image_analysis')
    op.create_index('ix_image_analysis_moderation_event_id', 'image_analysis', ['moderation_event_id'], unique=False)
    op.alter_column('image_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_metric_name'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_daily_analytics_id'), table_name='daily_analytics')
    op.drop_index(op.f('ix_daily_analytics_date'), table_name='daily_analytics')
    op.drop_table('daily_analytics')
    # ### end Alembic commands ###
